# Generated by Codex on 2026-05-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_anonymous_scans(apps, schema_editor):
    Scan = apps.get_model("scans", "Scan")
    Scan.objects.filter(user__isnull=True).delete()


def normalize_user_emails(apps, schema_editor):
    User = apps.get_model("auth", "User")
    seen = set()
    duplicate_ids = []

    for user in User.objects.exclude(email="").order_by("id"):
        normalized_email = user.email.strip().lower()
        if not normalized_email:
            continue
        if normalized_email in seen:
            duplicate_ids.append(user.id)
            continue
        seen.add(normalized_email)
        if user.email != normalized_email:
            user.email = normalized_email
            user.save(update_fields=["email"])

    if duplicate_ids:
        User.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("scans", "0004_alter_scan_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_anonymous_scans, migrations.RunPython.noop),
        migrations.RunPython(normalize_user_emails, migrations.RunPython.noop),
        migrations.RunSQL(
            sql=(
                "CREATE UNIQUE INDEX IF NOT EXISTS auth_user_email_ci_unique "
                "ON auth_user (LOWER(email)) WHERE email <> '';"
            ),
            reverse_sql="DROP INDEX IF EXISTS auth_user_email_ci_unique;",
        ),
        migrations.AlterField(
            model_name="scan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
